name: Build and publish Java project

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      release:
        required: false
        type: boolean
        default: false
      custom-version:
        required: false
        type: string
        default: ""
    secrets:
      SONATYPE_NEXUS_USERNAME:
        required: true
      SONATYPE_NEXUS_PASSWORD:
        required: true
      SONATYPE_GPG_ARMORED_KEY:
        required: true
      SONATYPE_SIGNING_PASSWORD:
        required: true

jobs:
  build-and-publish:
    name: Build and publish API
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Write custom release version to root file to prevent publishing release
        if: ${{ inputs.custom-version != '' }}
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: gradle.properties
          property: release_version
          value: ${{ inputs.custom-version }}
      - name: Write custom release version to file
        if: ${{ inputs.custom-version != '' }}
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: ${{ inputs.project-name }}/gradle.properties
          property: release_version
          value: ${{ inputs.custom-version }}
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - id: gradle-tasks
        run: echo ::set-output name=value::"--info --warning-mode all clean :${{ inputs.project-name }}:build :{{ inputs.project-name }}:publish"
      - name: Build release with Gradle
        if: inputs.release
        run: ./gradlew ${{ steps.gradle-tasks.outputs.value }} closeAndReleaseSonatypeStagingRepository
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
      - name: Build snapshot with Gradle
        if: ${{ !inputs.release }}
        run: ./gradlew ${{ steps.gradle-tasks.outputs.value }}
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}