name: Build and publish read db project

on:
  push:
    branches:
      - master
      - version-*
    paths:
      - grpc-sense/gradle.properties
      - sense-api/gradle.properties
      - sense-dsl/gradle.properties
      - sense-app/gradle.properties

jobs:
  changes:
    name: Collect changed files
    runs-on: ubuntu-20.04
    outputs:
      app: ${{ steps.filter.outputs.app }}
      api: ${{ steps.filter.outputs.api }}
      dsl: ${{ steps.filter.outputs.dsl }}
      grpc: ${{ steps.filter.outputs.grpc }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            app:
              - 'sense-app/gradle.properties'
            grpc:
              - 'grpc-sense/gradle.properties'
            api:
              - 'sense-api/gradle.properties'
            dsl:
              - 'sense-dsl/gradle.properties'
  build-and-publish-api:
    name: Build and publish API release
    if: ${{ needs.changes.outputs.api == 'true' }}
    needs:
      - changes
    uses: ./.github/workflows/build-and-publish-java.yml
    with:
      project-name: sense-api
      release: true
    secrets: inherit
  build-and-publish-dsl:
    name: Build and publish DSL release
    if: ${{ needs.changes.outputs.dsl == 'true' || needs.changes.outputs.api == 'true' }}
    needs:
      - changes
    uses: ./.github/workflows/build-and-publish-java.yml
    with:
      project-name: sense-dsl
      release: true
    secrets: inherit
  build-and-publish-java-grpc:
    name: Build and publish gRPC java release
    if: ${{ needs.changes.outputs.grpc == 'true' }}
    needs:
      - changes
    uses: ./.github/workflows/build-and-publish-java.yml
    with:
      project-name: grpc-sense
      release: true
    secrets: inherit
  build-and-publish-python-grpc:
    name: Build and publish gRPC Python release to PyPI
    if: ${{ needs.changes.outputs.grpc == 'true' }}
    needs:
      - changes
    uses: ./.github/workflows/build-and-publish-python.yml
    secrets: inherit
  build-and-publish-app:
    name: Build and publish core part for sense app
    if: |
      always() &&
      (needs.changes.outputs.app == 'true' ||
       needs.changes.outputs.grpc == 'true' ||
       needs.changes.outputs.dsl == 'true' ||
       needs.changes.outputs.api == 'true')
    needs:
      - build-and-publish-api
      - build-and-publish-dsl
      - build-and-publish-java-grpc
      - build-and-publish-python-grpc
    uses: ./.github/workflows/build-and-publish-java.yml
    with:
      project-name: sense-app
      release: true
    secrets: inherit
  owasp-scan-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run OWASP scanning
        run: ./gradlew dependencyCheckAggregate
      - name: Upload OWASP scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: './build/reports/dependency-check-report.sarif'