name: Build and publish dev build for read db project

on:
  push:
    branches-ignore:
      - master
      - version-*
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
jobs:
  versions:
    name: Collect versions
    runs-on: ubuntu-20.04
    outputs:
      dsl: ${{ steps.java_dsl_ver.outputs.value }}
      api: ${{ steps.java_api_ver.outputs.value }}
      grpc-java: ${{ steps.java_grpc_ver.outputs.value }}
      grpc-python: ${{ steps.python_grpc_ver.outputs.value }}
      app: ${{ steps.app_release_ver.outputs.value }}
      root: ${{ steps.root_release.outputs.value }}
    steps:
      - uses: actions/checkout@v2
      # Prepare custom build version
      - name: Get branch name
        id: branch
        run: echo ::set-output name=branch_name::${GITHUB_REF#refs/*/}
      - name: Get grpc release_version
        id: grpc_ver
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: grpc-sense/gradle.properties
          property: release_version
      - name: Get api release_version
        id: api_ver
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: sense-api/gradle.properties
          property: release_version
      - name: Get dsl release_version
        id: dsl_ver
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: sense-dsl/gradle.properties
          property: release_version
      - name: Get app release_version
        id: app_ver
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: sense-app/gradle.properties
          property: release_version
      - name: Get root release_version
        id: root_ver
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: gradle.properties
          property: release_version
      - name: Build custom release version
        id: app_release_ver
        run: echo ::set-output name=value::"${{ steps.app_ver.outputs.value }}-${{ steps.branch.outputs.branch_name }}-SNAPSHOT"
      - name: Build custom api release version for java
        id: java_api_ver
        run: echo ::set-output name=value::"${{ steps.api_ver.outputs.value }}-${{ steps.branch.outputs.branch_name }}-SNAPSHOT"
      - name: Build custom api release version for java
        id: java_dsl_ver
        run: echo ::set-output name=value::"${{ steps.dsl_ver.outputs.value }}-${{ steps.branch.outputs.branch_name }}-SNAPSHOT"
      - name: Build custom grpc release version for java
        id: java_grpc_ver
        run: echo ::set-output name=value::"${{ steps.grpc_ver.outputs.value }}-${{ steps.branch.outputs.branch_name }}-SNAPSHOT"
      - name: Build custom root release version
        id: root_release
        run: echo ::set-output name=value::"${{ steps.root_ver.outputs.value }}-${{ steps.branch.outputs.branch_name }}-SNAPSHOT"
      - name: Build custom grpc package version
        id: python_grpc_ver
        run: echo ::set-output name=value::"${{ steps.grpc_ver.outputs.value }}.dev${{ github.run_id }}"
      - name: Show app release version
        run: echo ${{ steps.app_release_ver.outputs.value }}
      - name: Show api release version
        run: echo ${{ steps.java_api_ver.outputs.value }}
      - name: Show dsl release version
        run: echo ${{ steps.java_dsl_ver.outputs.value }}
      - name: Show grpc java release version
        run: echo ${{ steps.java_grpc_ver.outputs.value }}
      - name: Show grpc python release version
        run: echo ${{ steps.python_grpc_ver.outputs.value }}
  changes:
    name: Collect changed files
    runs-on: ubuntu-20.04
    outputs:
      app: ${{ steps.filter.outputs.app }}
      api: ${{ steps.filter.outputs.api }}
      dsl: ${{ steps.filter.outputs.dsl }}
      grpc: ${{ steps.filter.outputs.grpc }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            app:
              - 'sense-app/**'
            grpc:
              - 'grpc-sense/**'
            api:
              - 'sense-api/**'
            dsl:
              - 'sense-dsl/**'
  build-and-publish-api:
    name: Build and publish API
    needs:
      - changes
      - versions
    uses: ./.github/workflows/build-and-publish-java.yml
    with:
      project-name: sense-api
      custom-version: ${{ needs.versions.outputs.api }}
    secrets: inherit
  build-and-publish-dsl:
    name: Build and publish DSL
    needs:
      - changes
      - versions
    uses: ./.github/workflows/build-and-publish-java.yml
    with:
      project-name: sense-dsl
      custom-version: ${{ needs.versions.outputs.dsl }}
    secrets: inherit
  build-and-publish-java-grpc:
    name: Build and publish gRPC java
    needs:
      - changes
      - versions
    uses: ./.github/workflows/build-and-publish-java.yml
    with:
      project-name: grpc-sense
      custom-version: ${{ needs.versions.outputs.grpc-java }}
    secrets: inherit
  build-and-publish-python-grpc:
    name: Build and publish Python gRPC to PyPI
    needs:
      - changes
      - versions
    uses: ./.github/workflows/build-and-publish-python.yml
    with:
      custom-version: ${{ needs.versions.outputs.grpc-python }}
    secrets: inherit
  build-and-publish-app:
    name: Build and publish core part for sense app
    needs:
      - build-and-publish-api
      - build-and-publish-dsl
      - build-and-publish-java-grpc
      - build-and-publish-python-grpc
      - versions
    uses: ./.github/workflows/build-and-publish-java.yml
    with:
      project-name: sense-app
      custom-version: ${{ needs.versions.outputs.app }}
    secrets: inherit