name: Build and publish dev build for read db project

on:
  push:
    branches-ignore:
      - master
      - version-*
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
jobs:
  versions:
    name: Collect versions
    runs-on: ubuntu-20.04
    outputs:
      dsl: ${{ steps.java_dsl_ver.outputs.value }}
      api: ${{ steps.java_api_ver.outputs.value }}
      grpc-java: ${{ steps.java_grpc_ver.outputs.value }}
      grpc-python: ${{ steps.python_grpc_ver.outputs.value }}
      app: ${{ steps.app_release_ver.outputs.value }}
      root: ${{ steps.root_release.outputs.value }}
    steps:
      - uses: actions/checkout@v2
      # Prepare custom build version
      - name: Get branch name
        id: branch
        run: echo ::set-output name=branch_name::${GITHUB_REF#refs/*/}
      - name: Get grpc release_version
        id: grpc_ver
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: grpc-sense/gradle.properties
          property: release_version
      - name: Get api release_version
        id: api_ver
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: sense-api/gradle.properties
          property: release_version
      - name: Get dsl release_version
        id: dsl_ver
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: sense-dsl/gradle.properties
          property: release_version
      - name: Get app release_version
        id: app_ver
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: sense-app/gradle.properties
          property: release_version
      - name: Get root release_version
        id: root_ver
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: gradle.properties
          property: release_version
      - name: Build custom release version
        id: app_release_ver
        run: echo ::set-output name=value::"${{ steps.app_ver.outputs.value }}-${{ steps.branch.outputs.branch_name }}-${{ github.run_id }}"
      - name: Build custom api release version for java
        id: java_api_ver
        run: echo ::set-output name=value::"${{ steps.api_ver.outputs.value }}-${{ steps.branch.outputs.branch_name }}-SNAPSHOT"
      - name: Build custom api release version for java
        id: java_dsl_ver
        run: echo ::set-output name=value::"${{ steps.dsl_ver.outputs.value }}-${{ steps.branch.outputs.branch_name }}-SNAPSHOT"
      - name: Build custom grpc release version for java
        id: java_grpc_ver
        run: echo ::set-output name=value::"${{ steps.grpc_ver.outputs.value }}-${{ steps.branch.outputs.branch_name }}-SNAPSHOT"
      - name: Build custom root release version
        id: root_release
        run: echo ::set-output name=value::"${{ steps.root_ver.outputs.value }}-${{ steps.branch.outputs.branch_name }}-SNAPSHOT"
      - name: Build custom grpc package version
        id: python_grpc_ver
        run: echo ::set-output name=value::"${{ steps.grpc_ver.outputs.value }}.dev${{ github.run_id }}"
      - name: Show app release version
        run: echo ${{ steps.app_release_ver.outputs.value }}
      - name: Show api release version
        run: echo ${{ steps.java_api_ver.outputs.value }}
      - name: Show dsl release version
        run: echo ${{ steps.java_dsl_ver.outputs.value }}
      - name: Show grpc java release version
        run: echo ${{ steps.java_grpc_ver.outputs.value }}
      - name: Show grpc python release version
        run: echo ${{ steps.python_grpc_ver.outputs.value }}
  changes:
    name: Collect changed files
    runs-on: ubuntu-20.04
    outputs:
      app: ${{ steps.filter.outputs.app }}
      api: ${{ steps.filter.outputs.api }}
      dsl: ${{ steps.filter.outputs.dsl }}
      grpc: ${{ steps.filter.outputs.grpc }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            app:
              - 'sense-app/**'
            grpc:
              - 'grpc-sense/**'
            api:
              - 'sense-api/**'
            dsl:
              - 'sense-dsl/**'
  build-and-publish-api:
    if: ${{ needs.changes.outputs.api == 'true' }}
    needs:
      - changes
      - versions
    uses: ./.github/workflows/build-and-publish-java.yml
    with:
      project-name: sense-api
      custom-version: ${{ needs.versions.outputs.api }}
    secrets: inherit
  build-and-publish-dsl:
    if: ${{ needs.changes.outputs.dsl == 'true' || needs.changes.outputs.api == 'true' }}
    needs:
      - changes
      - versions
    uses: ./.github/workflows/build-and-publish-java.yml
    with:
      project-name: sense-dsl
      custom-version: ${{ needs.versions.outputs.dsl }}
    secrets: inherit
  build-and-publish-java-grpc:
    if: ${{ needs.changes.outputs.grpc == 'true' }}
    needs:
      - changes
      - versions
    uses: ./.github/workflows/build-and-publish-java.yml
    with:
      project-name: grpc-sense
      custom-version: ${{ needs.versions.outputs.grpc-java }}
    secrets: inherit
  build-and-publish-python-grpc:
    name: Build and publish Python distributions to PyPI
    if: ${{ needs.changes.outputs.grpc == 'true' }}
    needs:
      - changes
      - versions
    uses: ./.github/workflows/build-and-publish-python.yml
    with:
      custom-version: ${{ needs.versions.outputs.grpc-python }}
    secrets: inherit
  build-and-publish-app:
    name: Build and publish core part for sense app
    if: |
      always() &&
      (needs.changes.outputs.app == 'true' ||
       needs.changes.outputs.grpc == 'true' ||
       needs.changes.outputs.dsl == 'true' ||
       needs.changes.outputs.api == 'true')
    needs:
      - build-and-publish-api
      - build-and-publish-dsl
      - build-and-publish-java-grpc
      - build-and-publish-python-grpc
      - versions
    uses: ./.github/workflows/build-and-publish-java.yml
    with:
      project-name: sense-app
      custom-version: ${{ needs.versions.outputs.app }}
    secrets: inherit


  build-and-publish-java:
    name: Build and publish Java distributions
    needs:
      - changes
      - versions
    runs-on: ubuntu-20.04
    if: ${{ needs.changes.outputs.grpc == 'true' }}
    steps:
      - uses: actions/checkout@v2
      - name: Write custom release version to root file to prevent publishing release
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: gradle.properties
          property: release_version
          value: ${{ needs.versions.outputs.root }}
      - name: Write custom release version to file
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: grpc/gradle.properties
          property: release_version
          value: ${{ needs.versions.outputs.grpc-java }}
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build with Gradle
        run: ./gradlew --info --warning-mode all clean :grpc-read-db:build :grpc-read-db:publish
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
  build-and-publish-python:
    name: Build and publish Python distributions to PyPI
    needs:
      - changes
      - versions
    runs-on: ubuntu-20.04
    if: ${{ needs.changes.outputs.grpc == 'true' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set version for current build in package_info.json
        uses: MerthinTechnologies/edit-json-action@v1
        with:
          filename: 'grpc/package_info.json'
          key: 'package_version'
          value: ${{ needs.versions.outputs.grpc-python }}
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build with Gradle
        run: ./gradlew clean :grpc-read-db:build
      - name: Build package
        working-directory: ./grpc
        run: |
          pip install -r requirements.txt
          python setup.py generate -s
          python setup.py sdist
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          repository_url: https://upload.pypi.org/legacy/
          packages_dir: grpc/dist/
  publish-docker:
    name: Bulid docker image
    runs-on: ubuntu-20.04
    needs:
      - build-and-publish-python
      - build-and-publish-java
      - versions
    if: |
      always() &&
      (needs.changes.outputs.app == 'true' || needs.changes.outputs.grpc == 'true')
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - run: echo "::set-output name=REPOSITORY_NAME::$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')"
        id: meta
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ needs.versions.outputs.app }}
          labels: com.exactpro.th2.${{ steps.meta.outputs.REPOSITORY_NAME }}=${{ needs.versions.outputs.app }}
          build-args: |
            release_version=${{ needs.versions.outputs.app }}